# Generated by Django 5.1.2 on 2025-07-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_companyprofile_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='companytour',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companytour',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
